//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KneadLMS
{
    public partial class AdminPanel
    {
        protected global::System.Web.UI.WebControls.Literal litAdminName;
        protected global::System.Web.UI.WebControls.Literal litAdminRole;
        protected global::System.Web.UI.WebControls.Literal litAdminInitials;

        protected global::System.Web.UI.WebControls.Literal litTotalUsers;
        protected global::System.Web.UI.WebControls.Literal litTotalCuisines;
        protected global::System.Web.UI.WebControls.Literal litTotalRecipes;
        protected global::System.Web.UI.WebControls.Literal litTotalQuizzes;

        protected global::System.Web.UI.WebControls.GridView gvUsers;

        protected global::System.Web.UI.WebControls.DropDownList ddlCourseCuisine;
        protected global::System.Web.UI.WebControls.DropDownList ddlRecipeCourseType;
        protected global::System.Web.UI.WebControls.DropDownList ddlStepRecipe;
        protected global::System.Web.UI.WebControls.DropDownList ddlQuizRecipe;
        protected global::System.Web.UI.WebControls.DropDownList ddlQuestionQuiz;

        protected global::System.Web.UI.WebControls.Panel pnlAdminMsg;
        protected global::System.Web.UI.WebControls.Literal litAdminMsg;

        protected global::System.Web.UI.WebControls.Button btnNavOverview;
        protected global::System.Web.UI.WebControls.Button btnNavCuisines;
        protected global::System.Web.UI.WebControls.Button btnNavRecipes;
        protected global::System.Web.UI.WebControls.Button btnNavQuizzes;

        protected global::System.Web.UI.WebControls.Panel pnlOverview;
        protected global::System.Web.UI.WebControls.Panel pnlCuisines;
        protected global::System.Web.UI.WebControls.Panel pnlRecipes;
        protected global::System.Web.UI.WebControls.Panel pnlQuizzes;

        protected global::System.Web.UI.WebControls.Button btnAddQuiz;
        protected global::System.Web.UI.WebControls.TextBox txtQuizTitle;
        protected global::System.Web.UI.WebControls.TextBox txtPassingScore;

        protected global::System.Web.UI.WebControls.Button btnAddQuestion;
        protected global::System.Web.UI.WebControls.TextBox txtQuestionText;
        protected global::System.Web.UI.WebControls.TextBox txtOptionA;
        protected global::System.Web.UI.WebControls.TextBox txtOptionB;
        protected global::System.Web.UI.WebControls.TextBox txtOptionC;
        protected global::System.Web.UI.WebControls.TextBox txtOptionD;
        protected global::System.Web.UI.WebControls.DropDownList ddlCorrectAns;

        // Additional admin controls
        protected global::System.Web.UI.WebControls.GridView gvAdminCuisines;
        protected global::System.Web.UI.WebControls.GridView gvAdminRecipes;
        protected global::System.Web.UI.WebControls.GridView gvAdminQuizzes;

        protected global::System.Web.UI.WebControls.TextBox txtNewCuisineName;
        protected global::System.Web.UI.WebControls.TextBox txtNewCuisineDesc;
        protected global::System.Web.UI.WebControls.TextBox txtNewCuisineImg;
        protected global::System.Web.UI.WebControls.HiddenField hfEditCuisineId;
        protected global::System.Web.UI.WebControls.Button btnAddCuisine;

        protected global::System.Web.UI.WebControls.TextBox txtCourseTypeName;

        protected global::System.Web.UI.WebControls.TextBox txtRecipeTitle;
        protected global::System.Web.UI.WebControls.TextBox txtRecipeDesc;
        protected global::System.Web.UI.WebControls.TextBox txtRecipeIngredients;
        protected global::System.Web.UI.WebControls.TextBox txtRecipeDuration;
        protected global::System.Web.UI.WebControls.DropDownList ddlRecipeDifficulty;
        protected global::System.Web.UI.WebControls.TextBox txtRecipeThumb;
        protected global::System.Web.UI.WebControls.TextBox txtRecipeVideo;

        protected global::System.Web.UI.WebControls.TextBox txtStepNumber;
        protected global::System.Web.UI.WebControls.TextBox txtStepInstruction;
        protected global::System.Web.UI.WebControls.TextBox txtStepImage;
        // Media manager controls
        protected global::System.Web.UI.WebControls.DropDownList ddlMediaRecipe;
        protected global::System.Web.UI.WebControls.TextBox txtMediaImageUrl;
        protected global::System.Web.UI.WebControls.FileUpload fuMediaImage;
        protected global::System.Web.UI.WebControls.TextBox txtMediaVideoUrl;
        protected global::System.Web.UI.WebControls.Button btnSaveMedia;
    }
}
