//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KneadLMS
{
    public partial class DefaultPage
    {
        protected global::System.Web.UI.WebControls.Literal litCuisineCount;
        protected global::System.Web.UI.WebControls.Literal litCourseTypeCount;
        protected global::System.Web.UI.WebControls.Literal litRecipeCount;
        protected global::System.Web.UI.WebControls.Literal litUserCount;

        protected global::System.Web.UI.WebControls.Repeater rptCuisines;
    }
}
