//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KneadLMS
{
    public partial class ForumDetail
    {
        protected global::System.Web.UI.WebControls.Literal litTopicTitle;
        protected global::System.Web.UI.WebControls.Literal litAuthorName;
        protected global::System.Web.UI.WebControls.Literal litTopicDate;
        protected global::System.Web.UI.WebControls.Literal litRecipeBadge;

        protected global::System.Web.UI.WebControls.Literal litCommentCount;
        protected global::System.Web.UI.WebControls.Repeater rptComments;
        protected global::System.Web.UI.WebControls.Panel pnlNoComments;

        protected global::System.Web.UI.WebControls.Button btnAddComment;
        protected global::System.Web.UI.WebControls.TextBox txtNewComment;
        protected global::System.Web.UI.WebControls.Panel pnlCommentError;
        protected global::System.Web.UI.WebControls.Literal litCommentError;
    }
}
