//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KneadLMS
{
    public partial class Forums
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlRecipeSelect;
        protected global::System.Web.UI.WebControls.TextBox txtSearchTopic;
        protected global::System.Web.UI.WebControls.Repeater rptTopics;
        protected global::System.Web.UI.WebControls.Panel pnlNoTopics;

        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnOpenNewTopic;
        protected global::System.Web.UI.WebControls.Panel pnlNewTopicForm;
        protected global::System.Web.UI.WebControls.TextBox txtTopicTitle;
        protected global::System.Web.UI.WebControls.TextBox txtInitialComment;
        protected global::System.Web.UI.WebControls.Panel pnlTopicError;
        protected global::System.Web.UI.WebControls.Literal litTopicError;
    }
}
