//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KneadLMS
{
    public partial class ItemList
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlCuisineFilter;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlDifficultyFilter;
        protected global::System.Web.UI.WebControls.Repeater rptRecipes;
        protected global::System.Web.UI.WebControls.Panel pnlNoResults;
        protected global::System.Web.UI.WebControls.Literal litSectionTitle;
        protected global::System.Web.UI.WebControls.Button btnSearch;
    }
}
