//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KneadLMS
{
    public partial class QuizDetail
    {
        protected global::System.Web.UI.WebControls.Literal litQuizTitle;
        protected global::System.Web.UI.WebControls.Literal litPassingScore;
        protected global::System.Web.UI.WebControls.Repeater rptQuestions;
        protected global::System.Web.UI.WebControls.Button btnSubmitQuiz;
        protected global::System.Web.UI.WebControls.Panel pnlQuestions;
        protected global::System.Web.UI.WebControls.Panel pnlResult;
        protected global::System.Web.UI.WebControls.Literal litResultHeadline;
        protected global::System.Web.UI.WebControls.Literal litResultScoreText;
    }
}
