//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KneadLMS
{
    public partial class QuizHistory
    {
        protected global::System.Web.UI.WebControls.Literal litSidebarName;
        protected global::System.Web.UI.WebControls.Literal litSidebarRole;
        protected global::System.Web.UI.WebControls.Literal litSidebarInitials;

        protected global::System.Web.UI.WebControls.GridView gvQuizHistory;
        protected global::System.Web.UI.WebControls.Panel pnlNoAttempts;
    }
}
