//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KneadLMS
{
    public partial class RecipeDetail
    {
        protected global::System.Web.UI.WebControls.Literal litRecipeTitle;
        protected global::System.Web.UI.WebControls.Literal litDescription;
        protected global::System.Web.UI.WebControls.Literal litDuration;
        protected global::System.Web.UI.WebControls.Literal litCuisineBadge;
        protected global::System.Web.UI.WebControls.Literal litCourseBadge;
        protected global::System.Web.UI.WebControls.Literal litDifficultyBadge;

        protected global::System.Web.UI.WebControls.HyperLink lnkBreadcrumbCuisine;
        protected global::System.Web.UI.WebControls.Literal litBreadcrumbCourse;

        protected global::System.Web.UI.WebControls.Image imgThumbnail;
        protected global::System.Web.UI.WebControls.HyperLink lnkPlayVideo;
        protected global::System.Web.UI.WebControls.HyperLink lnkForumDiscussions;

        protected global::System.Web.UI.WebControls.Literal litVideoTitle;
        protected global::System.Web.UI.WebControls.Literal litVideoDuration;

        protected global::System.Web.UI.WebControls.Repeater rptIngredients;
        protected global::System.Web.UI.WebControls.Repeater rptSteps;
        protected global::System.Web.UI.WebControls.Panel pnlNoSteps;

        protected global::System.Web.UI.WebControls.Literal litProgressPercent;
        protected global::System.Web.UI.WebControls.Panel pnlProgressFill;
        protected global::System.Web.UI.WebControls.Button btnMarkComplete;

        protected global::System.Web.UI.WebControls.Button btnSaveFavorite;
        protected global::System.Web.UI.WebControls.HyperLink lnkStartQuiz;
        protected global::System.Web.UI.WebControls.Label lblStatusMessage;
    }
}
