//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KneadLMS
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.WebControls.Panel pnlGuest;
        protected global::System.Web.UI.WebControls.Panel pnlUser;
        protected global::System.Web.UI.WebControls.Literal litUserName;
        protected global::System.Web.UI.WebControls.Literal litUserInitials;
        protected global::System.Web.UI.WebControls.HyperLink lnkUserProfile;
    }
}
