//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KneadLMS
{
    public partial class UserDashboard
    {
        protected global::System.Web.UI.WebControls.Literal litSidebarName;
        protected global::System.Web.UI.WebControls.Literal litSidebarRole;
        protected global::System.Web.UI.WebControls.Literal litSidebarInitials;

        protected global::System.Web.UI.WebControls.Literal litHeaderFirstName;
        protected global::System.Web.UI.WebControls.Literal litCompletedCount;
        protected global::System.Web.UI.WebControls.Literal litCuisinesInProgress;
        protected global::System.Web.UI.WebControls.Literal litAvgQuizScore;
        protected global::System.Web.UI.WebControls.Literal litForumTopicCount;

        protected global::System.Web.UI.WebControls.Repeater rptUserProgress;
        protected global::System.Web.UI.WebControls.Panel pnlNoProgress;

        protected global::System.Web.UI.WebControls.Repeater rptCuisineProgress;
        protected global::System.Web.UI.WebControls.Panel pnlNoCuisineProgress;
    }
}
